FROM fedora:37
ARG install_type_arg="basic"
ENV install_type=${install_type_arg}

RUN dnf install -y curl git

COPY envs/entrypoint.sh /tmp/entrypoint.sh
RUN chmod +x /tmp/entrypoint.sh

RUN useradd -m david
USER david
WORKDIR /home/david

ENTRYPOINT /tmp/entrypoint.sh $install_type