FROM ubuntu:22.04
ARG install_type="basic"

RUN apt-get update && apt-get install -y curl git

COPY envs/entrypoint.sh /tmp/entrypoint.sh
RUN chmod +x /tmp/entrypoint.sh

RUN useradd -m david
USER david
WORKDIR /home/david

ENTRYPOINT ["/tmp/entrypoint.sh", "${install_type}"]